# Generated by Django 4.2.20 on 2025-03-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
