# Generated by Django 4.2.20 on 2025-03-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_verification_code_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
